# Generated by Django 3.2.6 on 2021-08-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100)),
                ('edept', models.CharField(max_length=100)),
                ('salary', models.PositiveIntegerField()),
                ('exp', models.PositiveIntegerField()),
            ],
        ),
    ]
