# Generated by Django 3.2.6 on 2021-09-07 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100, unique=True)),
                ('author_name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('no_of_copies', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100, null=True)),
                ('images', models.ImageField(null='True', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('status', models.CharField(choices=[('Delivered', 'Delivered'), ('intransit', 'intransit'), ('ordered', 'ordered'), ('cancelled', 'cancelled')], default='ordered', max_length=20)),
                ('expected_delivery_date', models.DateField(null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.book')),
            ],
        ),
    ]
