# Generated by Django 3.2.6 on 2021-09-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='images',
            new_name='image',
        ),
    ]
