# Generated by Django 3.2.6 on 2021-09-08 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_rename_images_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateField(default=datetime.timedelta(days=5), null=True),
        ),
    ]
