# Generated by Django 3.2.6 on 2021-09-10 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_alter_order_expected_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateField(default=datetime.date(2021, 9, 15), null=True),
        ),
    ]
